version: '3'
services:
  educa:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Educa
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY=qWeE7yDdXH10WmxcPCf2J6EiTK-ZXI7fnpN1E8LJr_hOkCnWjxM
      - DJANGO_DEBUG=False
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_EMAIL_HOST=smtp.gmail.com
      - DJANGO_EMAIL_HOST_USER=lertonjosine@gmail.com
      - DJANGO_EMAIL_HOST_PASSWORD=adrrmefxpmtzmwmk
      - DJANGO_EMAIL_USE_TLS=True
      - DJANGO_EMAIL_PORT=587
      - DJANGO_SECURE_SSL_REDIRECT=True
      - DJANGO_SECURE_HSTS_SECONDS=2592000
      - DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=True
      - DJANGO_SECURE_HSTS_PRELOAD=True
      - DJANGO_SESSION_COOKIE_SECURE=True
      - DJANGO_CSRF_COOKIE_SECURE=True
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
    name: postgresql