# Generated by Django 5.1.5 on 2025-01-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustomizado',
            name='nome_do_pai',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
