# Generated by Django 5.1.5 on 2025-01-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariocustomizado_nome_do_pai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustomizado',
            name='nome_do_pai',
            field=models.CharField(default='', max_length=200),
        ),
    ]
