# Generated by Django 5.1.5 on 2025-01-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuariocustomizado_nome_do_pai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariocustomizado',
            options={'permissions': [('special_status', 'User can see all available courses')]},
        ),
    ]
