# Generated by Django 5.1.5 on 2025-01-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuariocustomizado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariocustomizado',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
